- name: "Apache Installation"
  yum:
    name: httpd
    state: present
  notify:
    - restart-httpd
    
- name: "PHP Installation"
  shell: amazon-linux-extras install php7.4 -y

- name: "Installation php extensions"
  yum:
    name: ['php-common','php-pear','php-cgi','php-curl','php-mbstring','php-mysqlnd','php-gd','php-gettext','php-json','php-xml','php-fpm','php-intl','php-zip']
    state: present
  notify:
    - restart-httpd
    
- name: "httpd.conf creation from template"
  template:
    src: httpd.conf.tmpl
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart-httpd

- name: "Virtualhost Creation from template"
  template:
    src: virtualhost.conf.tmpl 
    dest: "/etc/httpd/conf.d/{{ domain_name }}.conf"
  notify:
    - restart-httpd  

- name: "DocumentRoot Creation"
  file:
    path: "/var/www/html/{{ domain_name }}"
    state: directory
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
  notify:
    - restart-httpd    
 
- name: "info.php creation"
  copy:
    src: "info.php"
    dest: "/var/www/html/{{ domain_name }}/"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"

- name: "Mariadb Installation"
  yum:
    name: 
      - MySQL-python
      - mariadb-server
    state: present
      
- name: "Restarting/Enabling Mariadb Service"
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: "Changing Mariadb root password"
  ignore_errors: true
  mysql_user: 
    login_user: "root"
    login_password: ""
    user: "root"
    password: "{{ mariadb_root_password }}"
    host_all: true

- name: "Removing test database"  
  mysql_db:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "test"
    state: absent

- name : "Removing anonymous users"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    user: ""
    state: absent
    host_all: true

- name: "Creating new database"
  mysql_db:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ mariadb_database_name }}"
    state: present

- name: "Creating a new user"
  mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ mariadb_database_user_name }}"
    password: "{{ mariadb_database_user_password }}"
    priv: '{{ mariadb_database_name }}.*:ALL'
